name: Build

on:
  push:
    branches: [ main ]
  pull_request: # all pull requests
  workflow_dispatch: # allow triggering manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Set up Java 17'
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'maven'

      - name: 'Build'
        run: |
          xvfb-run mvn -V --batch-mode verify jacoco:report

      - name: 'Store results'
        uses: actions/upload-artifact@v3
        with:
          name: target
          path: target/

